#!/bin/bash

export BRANCH_ATTUALE=$(git rev-parse --abbrev-ref HEAD)
export BRANCH_ATTUALE_CAPITALIZED=${BRANCH_ATTUALE^}
export IMAGE_NAME=linhosan/em-ssl-decoder:${BRANCH_ATTUALE}

export NODEJS_PORT=4000
export NODEJS_PORT_ECLIPSE=${NODEJS_PORT}

if [[ "${BRANCH_ATTUALE}" == "dev" ]]; then
  NODEJS_PORT_ECLIPSE=4003
elif [[ "${BRANCH_ATTUALE}" == "bfx" ]]; then
  NODEJS_PORT_ECLIPSE=4005
fi

docker rm -f $(docker ps -aq --filter name=EM_SSL_Decoder_${BRANCH_ATTUALE_CAPITALIZED})
docker rmi ${IMAGE_NAME} 2>/dev/null
docker build --no-cache --rm -t ${IMAGE_NAME} .
docker run --env DEBUG=YES -d --restart unless-stopped \
  --privileged \
  --name EM_SSL_Decoder_${BRANCH_ATTUALE_CAPITALIZED}_Eclipse \
  --hostname EM_SSL_Decoder_${BRANCH_ATTUALE_CAPITALIZED}_Eclipse \
  -p ${NODEJS_PORT_ECLIPSE}:${NODEJS_PORT} \
  ${IMAGE_NAME}
