name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        file: Dockerfile
        push: true
        tags: linhosan/em-ssl-decoder:latest
